### ISSUE TITLE
CumulativeLayoutShift as WPT custom metric empty

### ISSUE THREAD

**Issue by e-orlov** [WICG/layout-instability#100]
Did exactly as in https://dev.to/chromiumdev/measuring-cumulative-layout-shift-cls-in-webpagetest-5cle: set command-line flag, script as custom metric, Dulles, VA, Canary. 

In opposite as in your test, i haven't on the right a link "custom metrics". If i manipulate your URL to custom metrics with my test ID i get displayed the same screen "Custom Metrics", where, however, the line with "CumulativeLayoutShift " on the left is empty. Looking into [raw JSON](https://www.webpagetest.org/jsonResult.php?test=210319_XiKH_f869ad8219d9aa1df15cbd83adb358fe&pretty=1) i see `"CumulativeLayoutShift": null,`.

Is this feature no longer supported by WPT? Or do i do something wrong because of any WPT change i don't know about?

**Comment by yoavweiss** [comment]
Hey @e-orlov!

Your question is not really related to this spec. You may want to ask it on WebPageTest's [support forums](https://forums.webpagetest.org/). I'm closing this as this is not actionable from a spec-perspective
