### ISSUE TITLE
When is the right time to start recording layout shifts?

### ISSUE THREAD

**Issue by rviscomi** [WICG/layout-instability#15]
Per the README:

```js
addEventListener("load", () => {
  let DCLS = 0;
  new PerformanceObserver((list) => {
      list.getEntries().forEach((entry) => { DCLS += entry.value; });
  }).observe({type: "layout-shift", buffered: true});
});
```

The `load` event seems like a deliberate choice, so I'm curious about the reasoning behind it, as opposed to an event like DOM Content Loaded. By starting at load time, won't that exclude layout shifts caused by unsized `<img>` elements in the document? Is the intention only to capture layout shifts caused by asynchronous resource loading?

**Comment by philipwalton** [comment]
The `buffered` flag is the answer to this concern. By passing `buffered: true` to `observe()`, you're saying you want to *also* get reports on layout shift entires that occurred prior to registering the PerformanceObserver.

The `buffered` flag has been in the [PerformanceObserver spec](https://www.w3.org/TR/performance-timeline-2/#dom-performanceobserverinit) for a while, but I think it's only been recently implemented by Chrome.

**Comment by skobes** [comment]
A recent patch enabled the buffered flag for layout shifts.

Some of the explainer (specifically the line that says "The observer is only notified of layout instability that occurs after it is registered") is out of date.  The layout shifts that occur before the `load` event will be delivered to the observer immediately.

https://github.com/WICG/layout-instability/pull/16 updates the explainer.
