### ISSUE TITLE
Attributes cannot accept sequence types - 'sources'

### ISSUE THREAD

**Issue by stephenmcgruer** [WICG/layout-instability#40]
The recent change to add LayoutShiftAttribution was just imported into WPT in https://github.com/web-platform-tests/wpt/pull/22499

The automatic idlharness file appears to have caught an error:

```
FAIL message: promise_test: Unhandled rejection with value: object "WebIDLParseError: Syntax error at line 11 in layout-instability, since `interface LayoutShift`:
 attribute sequence<LayoutShiftAttribution> sources;
                                            ^ Attributes cannot accept sequence types"
```

https://wpt.fyi/results/layout-instability/idlharness.window.html?diff&filter=ADC&run_id=441160005&run_id=460560003

**Comment by npm1** [comment]
Oh right... We probably want to have a method `getSources` then.

**Comment by skobes** [comment]
Why can't attributes be sequences?

**Comment by stephenmcgruer** [comment]
From https://heycam.github.io/webidl/#sequence-type:

> Sequences must not be used as the type of an attribute or constant.

> Note: This restriction exists so that it is clear to specification writers and API users that sequences are copied rather than having references to them passed around. Instead of a writable attribute of a sequence type, it is suggested that a pair of operations to get and set the sequence is used.

**Comment by skobes** [comment]
Hmm, we don't need pass-by-value.  Is there a better way to declare an array-like property of an object?

**Comment by skobes** [comment]
I am tempted to return to FrozenArray, though npm had concerns about that...

**Comment by npm1** [comment]
Ok, let's try FrozenArray for now. My concern is that it says the it has a `fixed length array of unmodifiable values.` From what I understand your list is fixed length but modifiable. That can be a question for the TAG too :)
