### ISSUE TITLE
arbitrary constants in the spec?

### ISSUE THREAD

**Issue by fred-wang** [WICG/layout-instability#47]
I noticed these:
- "5 members" ( https://wicg.github.io/layout-instability/#sec-report-layout-shift-sources )
- "3 or more pixel units" ( https://wicg.github.io/layout-instability/#sec-unstable-nodes )

Probably there is a good rationale for these values, but the spec does not explain from where they are coming.

(side note: As a comparison, the intersection observer spec which deals with similar approximations, introduced rootMargin / threshold values, so they are configurable by users)

**Comment by anniesullie** [comment]
"3 or more pixel units" is being addressed in #53, let's scope this down to discussion of "5 members" constant.

**Comment by npm1** [comment]
Regarding why 5, I believe it's arbitrary. We want to provide some good amount of attribution to enable developers to dig into the issues, but at the same time we don't want to spam developers with information nor have to store large amounts. I can add a note saying that this is arbitrary but for consistency it is good to have all user agents adopt the same number of members.
