### ISSUE TITLE
Explain (and perhaps make configurable) the magic number 3 in "3 or more pixel units" (when determining which nodes are shifted)

### ISSUE THREAD

**Issue by dholbert** [WICG/layout-instability#53]
Right now this section...
https://wicg.github.io/layout-instability/#sec-unstable-nodes
...defines "shifted" as the starting point having moved by 3 or more pixels in some axis.

Why the magic number 3?

A few thoughts about (and responses to) some possible explanations:
* If the point is to avoid penalizing small shifts: doesn't the "distance fraction" already sort of account for that?
* If the point is to simply reduce the computational cost on the browser: that reduced computational cost seems maybe nice, but it's not clear to me that 2px shifts are common enough to have their own special case here.

It seems like maybe this threshold should be configurable in the API -- or if not, there should be a clear explanation somewhere for why 3px is The Right Threshold.

**Comment by npm1** [comment]
I think the main reason 3 is chosen is to make the API performant. We could make it configurable by the user agent, though probably shouldn't make it configurable by the developer.

**Comment by dholbert** [comment]
3px is still pretty magic, though; presumably a higher threshold of 5px or 10px (or even `1rem` or `1vw`) would make it even more performant.  And on the flip side, a lower threshold of 1px would make it more correct (and 0.5px would make it even still more correct).

Can you clarify **why** a 1px threshold has significantly-worse-enough performance than 3px to rule that out? e.g. is there a lot of content with rapid 1px or 2px shifts that would overwhelm this API in a way that hurts performance (but not much content with >3px shifts that cause the same problem?)

I'm interested to hear/discuss the reasoning here, but it also would eventually be nice to include a `Note` in the spec to explain the choice of 3 and the drawbacks of going too small / too large.

Thinking out loud: some possible non-performance-related justifications that I can imagine [though I have no idea if these are the actual reasons]:
 - While small 1px shifts **are** user-perceivable, they're less likely to trigger the "clicked the wrong button" sort of pain-point which IIUC is a large motivator for this feature, so maybe we care less about shifts of that magnitude
 - Maybe allowing 1-2px shifts can allow for certain motion animations that don't want to penalize.  (i.e. maybe there was a judgement that 1-2px movement per paint is "smooth enough" for an animation to be user-pleasing, but significantly more is too jarring?)

**Comment by dholbert** [comment]
(To clarify: I'm not arguing for a different threshold and I'm not necessarily saying it should be UA-dependent, though if it is truly magic then perhaps it should be. I'm mostly just wanting to understand the reasoning, since it superficially seems pretty arbitrary.)

**Comment by npm1** [comment]
Hmm yea I think that Chrome uses 3 because we want to capture as much as possible and saw that there were some lab bots complaining when we had it at 1. I don't know if we tried 2 but overall it seems reasonable to me that the user agent could pick a value based on constraints of their implementation. Perhaps we can make it some variable used in the spec and mention in a Note that 3 is the value chosen by Chrome's implementation?

**Comment by dholbert** [comment]
That seems fine, though I still really want to understand **what specifically was problematic when you tried a value of 1** (and why, and how switching to 3 fixed it).  What sorts of content/movements seemed to be causing your lab bots to complain about performance when you used the 1px threshold?

In particular: was it for individual layout shifts that happen during pageload that are specifically only 1-2px in size (e.g. from resources loading)?  Or was it for slowly-animating content that's animated with abspos & `left` at 1px-per-frame?  Those are the sorts of things I can imagine causing reports at a 1px threshold but not at a 3px threshold, but intuitively I don't imagine either would be super-common.  Maybe there's another category that benefits here that I'm not thinking of?

**Comment by npm1** [comment]
@skobes can you provide some answer here? I'm also not sure what is very different performance-wise about 1px vs 3px.

**Comment by skobes** [comment]
I think it was an animation test, but I don't recall exactly.

**Comment by dholbert** [comment]
Hmm, ok.

It's not intuitively obvious to me why changing the threshold from 1px to 3px would make a substantial difference in an animation test... I have a nagging feeling that the testcase must have been animating a layout-impacting property at ~1-2px per animation-frame -- this would report a shift on every refresh if we use a 1px threshold, but it *never reports any shift at all* if we use a 3px threshold.  But a marginally-larger animation (animating 3px per animation-frame) would still have the same problem (reporting a shift on every tick).

I can't kick the feeling that this threshold feels pretty hacky, due to (a) the "all or nothing" stuff discussed above (3px-per-tick gets you horrible layout-shift-scores, 2px-per-tick gets you zero layout-shift-scores), and (b) the presence of this magic number.

**Comment by npm1** [comment]
Would you think it would be preferable to just surface every layout shift, i.e. remove the threshold? I wonder if we can try doing this change in Chrome to try to understand whether there is a valid reason for the 3px threshold.

**Comment by skobes** [comment]
Because multiplying by movement distance is part of the score calculation, there is hardly any difference between counting vs. not counting such small movements.  In my opinion we could just remove the 3px threshold from the spec, and the user agent could still implement such a threshold under the general allowance for trading off precision and efficiency.

**Comment by dholbert** [comment]
Just from the perspectives of understandability, theoretical purity/coherence, and avoiding the feature being "gameable"/arbitrary: yeah, I think it would be preferable to remove the threshold.

I can imagine there being cases where there's a lot of content moving and things would get heavyweight for the engine. But in those cases, your points in https://github.com/WICG/layout-instability/issues/52#issuecomment-651192820 suggest that you think this cost should only be measurable if the feature is being used (i.e. the mandatory `buffered` measurements aren't expected to ever be too expensive).  And if the feature *is* being used, then presumably the site would be interested to be informed about all their micro-shifts & the resulting relayout that they cause, so the cost is worth it.

**Comment by dholbert** [comment]
To have something concrete to look at, here are two testcases (where I'm assuming ~60 FPS):

- Here's a testcase with a ~2px-per-animation-frame movement, where Chrome reports **no layout shift**:
https://jsfiddle.net/dholbert/bwkvqm61/
- If I adjust the testcase to double the speed (so, ~4px-per-animation-frame), Chrome does report a layout shift:
https://jsfiddle.net/dholbert/bwkvqm61/1/

Chrome's behavior on these testcases matches the spec (honoring the 3px threshold), but it doesn't feel like it makes much sense.

**Comment by dholbert** [comment]
> Because multiplying by movement distance is part of the score calculation, there is hardly any difference between counting vs. not counting such small movements. 

For an individual animation-frame's measurement, perhaps this is true.  But if the moving thing is moving continuously for some period of time (i.e. being animated), then counting vs. not counting could make a huge difference in the CLS score (particularly if the rest of the page is mostly static).

> the user agent could still implement such a threshold under the general allowance for trading off precision and efficiency.

I agree with this, yeah.
