### ISSUE TITLE
Make transform behavior clearer in the spec

### ISSUE THREAD

**Issue by npm1** [WICG/layout-instability#59]
The explainer has a clear section about how transforms are treated by the API: https://github.com/WICG/layout-instability#transform-changes. However, it's not entirely clear to me where the spec enforces what the explainer is saying.

**Comment by wangxianzhu** [comment]
The mentioning of "local coordinate system" in https://wicg.github.io/layout-instability/#sec-unstable-nodes should make this clear, but currently it seems to fail to specify the situation that N itself creates a "local coordinate system", causing unclear meaning of
   3. P is not unstable
for descendants.
