### ISSUE TITLE
Spec appearance is broken

### ISSUE THREAD

**Issue by npm1** [WICG/layout-instability#76]
Right now when I go to https://wicg.github.io/layout-instability/ I see some portion of the page in black background and the rest in a light background that does not contrast well with the color of the text. Do you see this too @skobes ?

**Comment by anniesullie** [comment]
I'm not seeing this on Chrome 85.0.4183.102

**Comment by npm1** [comment]
This seems to be caused by bikeshed problems (see https://github.com/tabatkins/bikeshed/commit/b8157505dc80b8c89204abd0187d974124ee9c5f), so let's just push a trivial update to unbreak this.

**Comment by npm1** [comment]
Looks like this triggers because I have my Macbook on dark mode.

**Comment by tabatkins** [comment]
Regen the spec with latest version of Bikeshed, and this should be fixed.
