### ISSUE TITLE
Update usage of  hr-time "current high resolution time" algorithm 

### ISSUE THREAD

**Issue by igneel64** [WICG/layout-instability#78]
Based on the updated "current time high resolution time" on the [hr-time spec](https://w3c.github.io/hr-time/#dfn-current-high-resolution-time).

Change the [current high resolution time](https://wicg.github.io/layout-instability/#ref-for-dfn-current-high-resolution-time) definition to match the new algorithm defined in the hr-time spec.

**Comment by skobes** [comment]
What is the update that needs to be made here?

**Comment by npm1** [comment]
It needs to pass a global object. I think @igneel64 might want to tackle this on the hackathon next Tuesday though so no need to worry about this for now.

**Comment by igneel64** [comment]
Seems @npm1 beat me to it, but yes this issue was opened so that we conform to the **current high resolution time** algorithm requiring a global object to be passed to.
Will be PRed by us most probably 😄
