### ISSUE TITLE
`content-visibility: auto;` makes CLS go bananas

### ISSUE THREAD

**Issue by zeemawn** [WICG/layout-instability#89]
Hi, I've already posted this as an issue in the web-vitals repo but got referred here 🙂

https://github.com/GoogleChrome/web-vitals/issues/108

It seems like by using the new `content-visibility: auto;` the measured layout-shifts keep increasing while the user scrolls the page, even though the shifts are happening outside the visible viewport - is this a desired behavior?

The reported CLS-values can easily get to 1 and above just by scrolling down the page (even though for the user everything looks fine and non-jumpy).

**Comment by yoavweiss** [comment]
There was a Chromium implementation bug that was fixed. Do you still see an issue in e.g. Chrome Canary?

**Comment by skobes** [comment]
Let's use crbug.com/1164942 to track this issue.
