### ISSUE TITLE
Starting point shift with countering transform change should be ignored

### ISSUE THREAD

**Issue by wangxianzhu** [WICG/layout-instability#93]
Test case:
https://chromium-review.googlesource.com/c/chromium/src/+/2673965/6/third_party/blink/web_tests/external/wpt/layout-instability/transform-counter-layout-shift.html

This is a pattern used in many websites containing carousal UI, which moves elements smoothly using transform,
and when new contents is to be shifted in, resets the transform and add a countering layout offset, without any visual change.

**Comment by skobes** [comment]
@wangxianzhu Can you review #94 ?
